function ThermocalcbasedonEPMA = importfile2(workbookFile, sheetName, dataLines)
%IMPORTFILE2 Import data from a spreadsheet
%  THERMOCALCBASEDONEPMA = IMPORTFILE2(FILE) reads data from the first
%  worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the numeric data.
%
%  THERMOCALCBASEDONEPMA = IMPORTFILE2(FILE, SHEET) reads from the
%  specified worksheet.
%
%  THERMOCALCBASEDONEPMA = IMPORTFILE2(FILE, SHEET, DATALINES) reads
%  from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  ThermocalcbasedonEPMA = importfile2("C:\Users\Mark T\Dropbox (The University of Manchester)\PhD\Thermocalc\Thermocalc based on EPMA.xlsx", "High Alloy Band", [4, 1679]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 25-Apr-2022 12:22:03

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [4, 1679];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 13);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "D" + dataLines(1, 1) + ":P" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["TemperatureC", "VolumeFractionOfBCC_A2", "VolumeFractionOfC14_LAVES", "VolumeFractionOfFCC_A1", "VolumeFractionOfFCC_A12", "VolumeFractionOfHCP_A3", "VolumeFractionOfHCP_A32", "VolumeFractionOfLIQUID", "VolumeFractionOfM23C6_D84", "VolumeFractionOfM23C6_D842", "VolumeFractionOfM6C_E93", "VolumeFractionOfM7C3_D101", "VolumeFractionOfMC_ETA"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Import the data
ThermocalcbasedonEPMA = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "D" + dataLines(idx, 1) + ":P" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    ThermocalcbasedonEPMA = [ThermocalcbasedonEPMA; tb]; %#ok<AGROW>
end

%% Convert to output type
ThermocalcbasedonEPMA = table2array(ThermocalcbasedonEPMA);
end